# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).

dimensions = Dimension.create([
    {name: 'UC正史'},
    {name: 'SEED'},
    {name: '平成三部曲'}
  ])
p "Dimension done"

sides = Side.create([
  { name: 'DSSD'},
  { name: 'MO-V资源卫星防卫队'},
  { name: 'OZ'},
  { name: 'P3武装组织'},
  { name: 'Preventer'},
  { name: 'SIDE'},
  { name: 'ZAFT'},
  { name: '阿克泰昂'},
  { name: '阿纳海姆'},
  { name: '艾斯丹东王国'},
  { name: '奥布'},
  { name: '奥古'},
  { name: '白色芬古'},
  { name: '大天使号/永恒号'},
  { name: '抵抗组织'},
  { name: '地球联合军'},
  { name: '地球议会军'},
  { name: '地球住民'},
  { name: '回收屋'},
  { name: '火星独立吉恩军'},
  { name: '吉恩'},
  { name: '旧地球联邦'},
  { name: '巨蛇之尾'},
  { name: '卡拉巴'},
  { name: '联邦'},
  { name: '猎鹰'},
  { name: '马法迪'},
  { name: '玛莉美亚军'},
  { name: '民间'},
  { name: '木星帝国'},
  { name: '神圣军事同盟'},
  { name: '死亡先锋'},
  { name: '泰坦斯'},
  { name: '统一联合军'},
  { name: '新迪塞斯'},
  { name: '新地球联邦'},
  { name: '新吉恩'},
  { name: '宇宙革命军'},
  { name: '月面住民'},
  { name: '赞斯卡尔帝国'},
  { name: '殖民卫星'},
{ name: '殖民卫星联合'}
])


periods = Period.create([
    {:year=> '79',:name=> '',:dimension=>  dimensions.first},
    {:year=> '80',:name=> '',:dimension=>  dimensions.first},
    {:year=> '83',:name=> '',:dimension=>  dimensions.first},
    {:year=> '87',:name=> 'z',:dimension=>  dimensions.first},
    {:year=> '88',:name=> 'zz',:dimension=>  dimensions.first},
    {:year=> '92',:name=> '',:dimension=>  dimensions.first},
    {:year=> '93',:name=> '',:dimension=>  dimensions.first},
    {:year=> '99',:name=> '',:dimension=>  dimensions.first},
    {:year=> '123',:name=> '',:dimension=>  dimensions.first},
    {:year=> '',:name=> 'SEED',:dimension=>  dimensions[1]},
    {:year=> '',:name=> 'SEED Destiny',:dimension=>  dimensions[1]},
    {:year=> '',:name=> 'G',:dimension=>  dimensions[2]},
    {:year=> '',:name=> 'W',:dimension=>  dimensions[2]}
  ])
p "Period done"

Driver.create([
    {name: '夏亚'},
    {name: '阿姆罗'},
    {name: '黑色三连星'},
    {name: '爱微'},
    {name: '米哈伊尔·卡明斯基'},
    {name: '爱丽斯'},
    {name: '西罗.亚玛达'},
    {name: '麦克白'},
    {name: '西蒙'},
    {name: '卡多'}
  ])
p "Driver done"

usages = Usage.create([
    {name: '陆战用ms'},
    {name: '水下战用ms'},
    {name: '母舰'},
    {name: '地球圈战用ms'},
    {name: '宇宙战用ms'}
  ])
p "Usage done"

if usages.first.id && periods.first.id
  Gundam.create([
      { model: 'F71', name: 'G-GANNON', name_chs: 'G加农', period: periods.first ,usage: usages.first},
      { model: 'MS-05B', name: 'ZAKU I', name_chs: '扎古I后期型', period: periods.first ,usage: usages.first},
      { model: 'MS-05S', name: 'ZAKU I', name_chs: '扎古I指挥官用型', period: periods.first ,usage: usages.first},
      { model: 'MS-06F/J', name: 'ZAKU II F/J', name_chs: '扎古II F', period: periods.first ,usage: usages.first},
      { model: 'MS-06S', name: 'ZAKU II COMMANDER TYPE', name_chs: '扎古II指挥官用型', period: periods.first ,usage: usages.first},
      { model: 'MS-07B', name: 'GOUF', name_chs: '老虎', period: periods.first ,usage: usages.first},
      { model: 'MS-09', name: 'DOM', name_chs: '大魔', period: periods.first ,usage: usages.first},
      { model: 'MSM-03', name: 'GOGG', name_chs: '战蟹', period: periods.first ,usage: usages.first},
      { model: 'RX-75', name: 'GUNTANK', name_chs: '钢坦克', period: periods.first ,usage: usages.first},
      { model: 'RX-77-2', name: 'GUNGANNON', name_chs: '钢加农', period: periods.first ,usage: usages.first},
      { model: 'RX-78-1', name: 'GUNDAM', name_chs: '高达原型机', period: periods.first ,usage: usages.first},
      { model: 'RX-78-2', name: 'GUNDAM', name_chs: '高达', period: periods.first ,usage: usages.first},
      { model: 'RX-78-3', name: 'GUNDAM G3', name_chs: 'G3高达', period: periods.first ,usage: usages.first},
      { model: 'RX-78-4', name: '4TH GUNDAM', name_chs: '高达4号机', period: periods.first ,usage: usages.first},
      { model: 'RX-78-5', name: '5TH GUNDAM', name_chs: '高达5号机', period: periods.first ,usage: usages.first},
      { model: 'MS-18E', name: 'KAMPFER', name_chs: '京宝樊', period: periods[1] ,usage: usages.first},
      { model: 'MSM-03C', name: 'HYGOGG', name_chs: '高战蟹', period: periods[1] ,usage: usages.first},
      { model: 'MSM-07', name: 'Z\'GOK', name_chs: '魔蟹', period: periods[1] ,usage: usages.first},
      { model: 'RGM-79C', name: 'GM KAI', name_chs: '吉姆改', period: periods[1] ,usage: usages.first},
      { model: 'RGM-79G', name: 'GM', name_chs: '吉姆', period: periods[1] ,usage: usages.first},
      { model: 'RX-77D', name: 'Guncannon Mass Production', name_chs: '量产型钢加农', period: periods[1] ,usage: usages.first},
      { model: 'RX-78NT1', name: 'GUNDAM G-4 ALEX', name_chs: '爱利克斯高达', period: periods[1] ,usage: usages.first},
      { model: 'RX-79[G]', name: '', name_chs: '陆战高达先行量产型', period: periods[1] ,usage: usages.first},
      { model: 'RX-79[G]EZ-8', name: 'GUNDAM EZ8', name_chs: '高达EZ8', period: periods[1] ,usage: usages.first},
      { model: 'YMS-15', name: 'GANN', name_chs: '强人', period: periods[1] ,usage: usages.first},
      { model: 'AGX-04', name: 'GERBERA-TETRA', name_chs: '红色角马', period: periods[2] ,usage: usages.first},
      { model: 'AMX-002', name: 'NEUE ZIEL', name_chs: '露维.吉露', period: periods[2] ,usage: usages.first},
      { model: 'EX-16', name: 'ALBION', name_chs: '阿鲁比昂', period: periods[2] ,usage: usages.first},
      { model: 'MA-06', name: 'VAL-WALO', name_chs: '瓦尔.瓦罗', period: periods[2] ,usage: usages.first},
      { model: 'MS-06F2', name: 'ZAKU II F2', name_chs: '联邦用扎古II', period: periods[2] ,usage: usages.first},
      { model: 'MS-14A', name: 'GELGOOG', name_chs: '量产型格罗古古', period: periods[2] ,usage: usages.first},
      { model: 'MSN-00100', name: 'HYAKU SHIKI', name_chs: '百式', period: periods[2] ,usage: usages.first},
      { model: 'MSN-02', name: 'ZEONG', name_chs: '吉恩号', period: periods[2] ,usage: usages.first},
      { model: 'RMS-106', name: 'HI-ZAKU', name_chs: '高扎古', period: periods[2] ,usage: usages.first},
      { model: 'RX-178', name: 'GUNDAM MK-II', name_chs: '高达MK-II', period: periods[2] ,usage: usages.first},
      { model: 'RX-78 GP01', name: 'GUNDAM ZEPHYRANTHES', name_chs: '高达试作一号机', period: periods[2] ,usage: usages.first},
      { model: 'RX-78 GP01-FB', name: 'ZEPHYRANTHES FULL-VERNIAN', name_chs: '高达试作一号机', period: periods[2] ,usage: usages.first},
      { model: 'RX-78 GP02A', name: 'GUNDAM PHYSALIS', name_chs: '高达试作二号机', period: periods[2] ,usage: usages.first},
      { model: 'RX-78 GP03D', name: 'GUNDAM DENDROBIUM', name_chs: '高达试作三号机', period: periods[2] ,usage: usages.first},
      { model: 'RMS-141', name: 'XEKU-EINS', name_chs: '扎克艾因', period: periods[2] ,usage: usages.first},
      { model: 'AMX-004', name: 'QUBELEY', name_chs: '卡碧尼', period: periods[3] ,usage: usages.first},
      { model: 'EX-18', name: 'ARGAMA', name_chs: '亚迦玛', period: periods[3] ,usage: usages.first},
      { model: 'MSZ-006', name: 'ZETA GUNDAM', name_chs: 'Z高达', period: periods[3] ,usage: usages.first},
      { model: 'PMX-003', name: 'THE.O', name_chs: '铁奥', period: periods[3] ,usage: usages.first},
      { model: 'AMX-011', name: 'ZAKU III', name_chs: '扎古III', period: periods[4] ,usage: usages.first},
      { model: 'AMX-011S', name: 'ZAKU III CUSTOM', name_chs: '扎古III改', period: periods[4] ,usage: usages.first},
      { model: 'AMX-107', name: 'BAWOO', name_chs: '龙飞', period: periods[4] ,usage: usages.first},
      { model: 'FA-010-A', name: 'FULL ARMOR ZZ GUNDAM A', name_chs: '全装备ZZ高达A型', period: periods[4] ,usage: usages.first},
      { model: 'FA-010-S', name: 'FULL ARMOR ZZ GUNDAM S', name_chs: '全装甲ZZ高达S型', period: periods[4] ,usage: usages.first},
      { model: 'MSA-0011', name: 'SUPERIOR GUNDAM', name_chs: 'S高达', period: periods[4] ,usage: usages.first},
      { model: 'MSA-0011[EXT]', name: 'EXTRAORDINARILY SUPERIOR GUNDAM', name_chs: 'EX-S高达', period: periods[4] ,usage: usages.first},
      { model: 'MSA-099', name: 'RICK DIAS', name_chs: '利克迪亚斯', period: periods[4] ,usage: usages.first},
      { model: 'MSZ-008', name: 'Z II', name_chs: '', period: periods[4] ,usage: usages.first},
      { model: 'MSZ-010', name: 'ZZ GUNDAM', name_chs: 'ZZ高达', period: periods[4] ,usage: usages.first},
      { model: 'ORX-005', name: 'GAPLANT', name_chs: '贾普兰', period: periods[4] ,usage: usages.first},
      { model: 'RGZ-91', name: 'RE-GZ', name_chs: '灵格斯', period: periods[5] ,usage: usages.first},
      { model: 'MSN-04', name: 'SAZABI', name_chs: '沙扎比', period: periods[6] ,usage: usages.first},
      { model: 'RX-93', name: 'νGUNDAM', name_chs: 'v高达', period: periods[6] ,usage: usages.first},
      { model: 'RX-93-ν2', name: 'HI-νGUNDAM', name_chs: '海牛高达', period: periods[6] ,usage: usages.first},
      { model: 'MSN-06S', name: 'SINANJU', name_chs: '新安洲', period: periods[7] ,usage: usages.first},
      { model: 'NZ-666', name: 'kashatriya', name_chs: '剎帝利', period: periods[7] ,usage: usages.first},
      { model: 'RX-0', name: 'Unicorn Gundam', name_chs: '独角兽', period: periods[7] ,usage: usages.first},
      { model: 'RGM-109', name: 'HEAVYGUN', name_chs: '赫维刚', period: periods[8] ,usage: usages.first},
      { model: 'RX-F91', name: 'Gundam F91', name_chs: '高达 F91', period: periods[8] ,usage: usages.first},
      { model: 'RXR-44', name: 'GUNTANK R-44', name_chs: '钢坦克R-44', period: periods[8] ,usage: usages.first},
      { model: 'XM-01', name: 'DEN AN ZON', name_chs: '德南.佐恩', period: periods[8] ,usage: usages.first},
      { model: 'XM-05', name: 'BERGA GIROS', name_chs: '贝尔格.基罗斯', period: periods[8] ,usage: usages.first},
      { model: 'XM-06', name: 'DAHGI IRIS', name_chs: '达基.伊里斯', period: periods[8] ,usage: usages.first},
      { model: 'XM-07', name: 'VIGNA GHINA', name_chs: '比基那.基那', period: periods[8] ,usage: usages.first},
      { model: 'XM-X2', name: 'CROSS BONE GUNDAM X2', name_chs: '十字先锋高达二号机', period: periods[8] ,usage: usages.first},


      { model: 'AMF-101', name: 'DINN', name_chs: '', period: periods[9] ,usage: usages[0]},
      { model: 'CAT-X1/3', name: 'HYPERION GUNDAM', name_chs: '', period: periods[9] ,usage: usages.first},
      { model: 'GAT-01', name: 'Strike Dagger', name_chs: '', period: periods[9] ,usage: usages.first},
      { model: 'GAT-X102', name: 'DUEL GUNDAM', name_chs: '', period: periods[9] ,usage: usages.first},
      { model: 'GAT-X103', name: 'BUSTER GUNDAM', name_chs: '', period: periods[9] ,usage: usages.first},
      { model: 'GAT-X105', name: 'STRIKE GUNDAM', name_chs: '强袭高达', period: periods[9] ,usage: usages.first},
      { model: 'GAT-X131', name: 'CALAMITY GUNDAM', name_chs: '', period: periods[9] ,usage: usages.first},
      { model: 'GAT-X207', name: 'BLITZ GUNDAM', name_chs: '', period: periods[9] ,usage: usages.first},
      { model: 'GAT-X252', name: 'FORBIDDEN GUNDAM', name_chs: '', period: periods[9] ,usage: usages.first},
      { model: 'GAT-X303', name: 'AEGIS GUNDAM', name_chs: '', period: periods[9] ,usage: usages.first},
      { model: 'GAT-X370', name: '', name_chs: '劫掠高达', period: periods[9] ,usage: usages.first},
      { model: 'MBF-02', name: 'STRIKE ROUGE', name_chs: '嫣红强袭', period: periods[9] ,usage: usages.first},
      { model: 'MBF-M1', name: 'ASTRAY', name_chs: '', period: periods[9] ,usage: usages.first},
      { model: 'MBF-P01', name: 'GUNDAM ASTRAY 01', name_chs: '', period: periods[9] ,usage: usages.first},
      { model: 'MBF-P02', name: 'GUNDAM ASTRAY 02', name_chs: '红色异端', period: periods[9] ,usage: usages.first},
      { model: 'MBF-P03', name: 'GUNDAM ASTRAY 03', name_chs: '蓝色异端', period: periods[9] ,usage: usages.first},
      { model: 'UMF-4A', name: 'GOOHN', name_chs: '', period: periods[9] ,usage: usages.first},
      { model: 'ZGMF-1017', name: 'GINN', name_chs: '', period: periods[9] ,usage: usages.first},
      { model: 'ZGMF-1017M', name: '', name_chs: '高机动吉恩', period: periods[9] ,usage: usages.first},
      { model: 'ZGMF-515', name: 'CGUE', name_chs: '', period: periods[9] ,usage: usages.first},
      { model: 'ZGMF-600', name: 'GUAIZ', name_chs: '', period: periods[9] ,usage: usages.first},
      { model: 'ZGMF-X09A', name: 'JUSTICE GUNDAM', name_chs: '正义高达', period: periods[9] ,usage: usages.first},
      { model: 'ZGMF-X10A', name: 'FREEDOM GUNDAM', name_chs: '自由高达', period: periods[9] ,usage: usages.first},
      { model: 'ZGMF-X13A', name: 'PROVIDENCE GUNDAM', name_chs: '', period: periods[9] ,usage: usages.first},
      { model: 'ZGMF-X20A', name: 'Strike Freedom Gundam', name_chs: '强袭自由', period: periods[10] ,usage: usages.first},
      { model: 'ZGMF-X42S', name: 'Destiny Gundam', name_chs: '命运高达', period: periods[10] ,usage: usages.first},
      { model: 'ZGMF-X56S', name: 'Impulse gundam', name_chs: '', period: periods[10] ,usage: usages.first},

      { model: 'GF13-001NHII', name: 'MASTER GUNDAM', name_chs: '', period: periods[10] ,usage: usages.first},
      { model: 'GF13-017NJ', name: 'SHINING GUNDAM', name_chs: '闪光高达', period: periods[10] ,usage: usages.first},
      { model: 'GF13-017NJII', name: 'GOD GUNDAM', name_chs: '神高达', period: periods[10] ,usage: usages.first},
      { model: 'GF13-021NG', name: 'GUNDAM SPIFGEL', name_chs: '', period: periods[10] ,usage: usages.first},
      { model: 'MRX-009', name: 'PSYCO GUNDAM', name_chs: '精神力高达', period: periods[10] ,usage: usages.first},
      { model: 'MMS-01', name: 'SERPENT CUSTOM', name_chs: '', period: periods[11] ,usage: usages.first},
      { model: 'XXXG-00W0', name: 'Wing Zero', name_chs: '飞翼零式', period: periods[11] ,usage: usages.first}
    ])
  p "Gundam done"
end

p "all done!"