class GundamPhoto < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  include MongoSync

  # security (i.e. attr_accessible) ...........................................
  attr_accessible :image, :remote_image_url

  # relationships .............................................................
  belongs_to  :gundam

  # validations ...............................................................
  validates :image, :presence => true

  # callbacks .................................................................
  # 解决mongo数据无法被同步更新的问题
  after_save do 
    mongo.update_attribute(:image, self.attributes["image"])
  end
  
  # scopes ....................................................................
  scope :verified, where(:is_verified => true)
  scope :unverified, where(:is_verified => false)

  # additional config .........................................................
  mount_uploader :image, GundamPhotoUploader

  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end