class RawGundam < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  attr_accessible :url, :period, :name, :name_chs, :name_jp, :model, :usage, :force, :story, :manufactory, :specifications, :internal_environment, :measurement, :weight, :armor, :output, :propulsion, :acceleration, :special_equipped, :default_weapon, :selected_weapon, :hand_weapon, :ranged_weapon, :summary, :created_at, :updated_at, :is_processed, :gundam_id

  # relationships .............................................................
  belongs_to :gundam

  # validations ...............................................................
  validates :url, :uniqueness => true

  # callbacks .................................................................
  # scopes ....................................................................
  scope :not_processed, where("is_processed is not true")

  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end